// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleAppsScriptType
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Calendar add-on manifest.
public struct CalendarAddOnManifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Defines an endpoint that will be executed contexts that don't
  /// match a declared contextual trigger. Any cards generated by this function
  /// will always be available to the user, but may be eclipsed by contextual
  /// content when this add-on declares more targeted triggers.
  ///
  /// If present, this overrides the configuration from
  /// `addOns.common.homepageTrigger`.
  public var homepageTrigger: GoogleAppsScriptType.HomepageExtensionPoint? = nil

  /// Defines conference solutions provided by this add-on.
  public var conferenceSolution: [ConferenceSolution] = []

  /// An endpoint to execute that creates a URL to the add-on's settings page.
  public var createSettingsUrlFunction: Swift.String = Swift.String()

  /// An endpoint to trigger when an event is opened (viewed/edited).
  public var eventOpenTrigger: CalendarExtensionPoint? = nil

  /// An endpoint to trigger when the open event is updated.
  public var eventUpdateTrigger: CalendarExtensionPoint? = nil

  /// Define the level of data access when an event addon is triggered.
  public var currentEventAccess: CalendarAddOnManifest.EventAccess =
    CalendarAddOnManifest.EventAccess()

  /// Initialize a new instance of `CalendarAddOnManifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CalendarAddOnManifest().with { $0.homepageTrigger = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An enum defining the level of data access event triggers require.
  public enum EventAccess: Codable, Equatable, Sendable {
    /// Default value when nothing is set for EventAccess.
    case unspecified
    /// METADATA gives event triggers the permission to access the metadata of
    /// events such as event id and calendar id.
    case metadata
    /// READ gives event triggers access to all provided event fields including
    /// the metadata, attendees, and conference data.
    case read
    /// WRITE gives event triggers access to the metadata of events and the
    /// ability to perform all actions, including adding attendees and setting
    /// conference data.
    case write
    /// READ_WRITE gives event triggers access to all provided event fields
    /// including the metadata, attendees, and conference data and the ability to
    /// perform all actions.
    case readWrite
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .metadata: return 1
      case .read: return 3
      case .write: return 4
      case .readWrite: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .metadata: return "METADATA"
      case .read: return "READ"
      case .write: return "WRITE"
      case .readWrite: return "READ_WRITE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventAccess/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "METADATA": self = .metadata
      case "READ": self = .read
      case "WRITE": self = .write
      case "READ_WRITE": self = .readWrite
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventAccess/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .metadata
      case 3: self = .read
      case 4: self = .write
      case 5: self = .readWrite
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .metadata: return try container.encode(1)
      case .read: return try container.encode(3)
      case .write: return try container.encode(4)
      case .readWrite: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.calendar.CalendarAddOnManifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
