// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines conference related values.
public struct ConferenceSolution: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The endpoint to call when ConferenceData should be created.
  public var onCreateFunction: Swift.String = Swift.String()

  /// Required. IDs should be unique across ConferenceSolutions within one
  /// add-on, but this is not strictly enforced. It is up to the add-on developer
  /// to assign them uniquely, otherwise the wrong ConferenceSolution may be
  /// used when the add-on is triggered. While the developer may change the
  /// display name of an add-on, the ID should not be changed.
  public var id: Swift.String = Swift.String()

  /// Required. The display name of the ConferenceSolution.
  public var name: Swift.String = Swift.String()

  /// Required. The URL for the logo image of the ConferenceSolution.
  public var logoUrl: Swift.String = Swift.String()

  /// Initialize a new instance of `ConferenceSolution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConferenceSolution().with { $0.onCreateFunction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.apps.script.type.calendar.ConferenceSolution"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
